version: '2.0'
services:
  wordpress:
    image: wordpress-container:1.0
    container_name: wordpress
    ports:
      - 3200:80
    depends_on:
      - mysql-block
  mysql-block:
    image: mysql-container:1.0
    container_name: mysql
networks:
  default:
    external:
      name: pre-existing-network

